# Generated by Django 4.1.7 on 2023-03-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_user_data_rename_user_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
