from django.urls import path
from backendapp import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('about/', views.index, name='about'),
    path('features/', views.index, name='features'),
    path('login/', views.login, name='login'),
    path('teacher_login/', views.teacher_login, name='login'),
    path('login_page/', views.login_page, name='login_page'),
    path('landingpage1/', views.landingpage1, name='landingpage1'),
    path('landingpage2/',views.landingpage2, name='landingpage2'),
    path('attempt_quiz/',views.attemp_quiz, name='attemp_quiz'),
    path('view_quiz/',views.view_quiz, name='view_quiz'),
    path('view_selected_responses/',views.view_selected_responses, name='view_selected_responses'),
    path('view_my_responses/',views.view_my_responses, name='view_my_responses'),
    path('view_selected_responses_stu/',views.view_selected_responses_stu, name='view_selected_responses_stu'),
    path('view_selected_responses_r/',views.view_selected_responses_r, name='view_selected_responses_r'),
    path('test_portal/',views.index, name='test_portal'),
    path('test_que/',views.index, name='test_que'),
    path('stu_resp/',views.index, name='stu_resp'),
    path('selected_responses/',views.index, name='selected_responses'),
    path('selected_responses_stu/',views.index, name='selected_responses_stu'),
    path('test/',views.test, name='test'),
    path('view_test/',views.view_test, name='view_test'),
    path('stu_responses/',views.stu_responses, name='stu_responses'),
    path('rules/', views.index, name='rules'),
    path('rules2/', views.index, name='rules'),
    path('logout/',views.logout, name='logout'),
    path('questions/', views.questions, name='questions'),
    path('exam_que/', views.exam, name='exam_questions'),
    path('exam_que_t/', views.exam_t, name='exam_questions'),
    path('exam_created/', views.exam_created, name='exam_created'),
    path('answers/', views.answers, name='exam_questions'),
    path('responses/', views.responses, name='responses'),
    path('value_checker/', views.value_checker, name='value_checker'),
    path('attempted_quizzes/', views.index, name='attempted_quizzes'),
    path('my_quizzes/', views.my_quizzes, name='my_quizzes'),
]
